### ISSUE TITLE
[Feature Request] ReportRTS integration

### ISSUE THREAD

**Issue by HeroCC** [perfah/Bukkit-Duties#2]
ReportRTS is a tickets plugin that has a function that turns on and off 'Duty Mode' for the plugin. It has an API and would be a great addition to this plugin!

Link: http://dev.bukkit.org/bukkit-plugins/reportrts/

**Comment by perfah** [comment]
Hi, sorry for not replying for 5 years. I had forgotten about my old account. Is this still of interest?

**Comment by HeroCC** [comment]
Haha thanks for replying, a late response is better than none. I personally don't use ReportRTS anymore (and it doesn't look like it has been updated since I made this ticket), so I have no use for it. Unless anyone else says otherwise, feel free to close this.

**Comment by perfah** [comment]
haha yeah I realize the absurdity in answering this late! It was a good suggestion nonetheless.
